return {
	"zaldih/themery.nvim",
	lazy = false,
	config = function()
		require("themery").setup({
			themes = {
				"adwaita",
				"apprentice",
				"aurora",
				"ayu-dark",
				"ayu-mirage",
				"bamboo",
				"bluloco-dark",
				"bluloco-light",
				"catppuccin-mocha",
				"cobalt2",
				"dracula",
				"eldritch",
				"embark",
				"everforest",
				"gruvbox",
				"gruvbox-material",
				"kanagawa",
				"kanso",
				"lunaperche",
				"materialbox",
				"meadow",
				"mfd",
				"modus_operandi",
				"modus_vivendi",
				"moonfly",
				"nightfox",
				"okcolors",
				"onedark",
				"rose-pine-main",
				"solarized-osaka-night",
				"sonokai",
				"space-vim-dark",
				"stoics",
				"tokyodark",
				"tokyonight-moon",
				"tokyonight-storm",
				"vision",
				"visual_studio_code",
				"wisteria",
				"vividchalk",
				"zaibatsu",
			},
			livePreview = true,
		})
	end,
}
