return {
  'zaldih/themery.nvim',
  lazy = false,
  config = function()
    require('themery').setup({
      themes = {
        'adwaita',
        'apprentice',
        'aurora',
        'ayu-dark',
        'ayu-mirage',
        'bluloco-dark',
        'bluloco-light',
        'catppuccin-mocha',
        'cobalt2',
        'dracula',
        'eldritch',
        'everforest',
        'gruvbox',
        'gruvbox-material',
        'kanagawa',
        'lunaperche',
        'modus_operandi',
        'modus_vivendi',
        'moonfly',
        'nightfox',
        'onedark',
        'rose-pine-main',
        'solarized-osaka-night',
        'sonokai',
        'stoics',
        'tokyodark',
        'tokyonight-moon',
        'tokyonight-storm',
        'vague',
        'vision',
        'visual_studio_code',
        'vividchalk',
        'zaibatsu',
      },
      livePreview = true,
    })
  end,
}
